-- MySQL Script generated by MySQL Workbench
-- Sun Nov 23 22:43:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema airportdata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airportdata
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airportdata` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `airportdata` ;

-- -----------------------------------------------------
-- Table `airportdata`.`airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`airline` (
  `airline_ID` INT NOT NULL,
  `unique_carrier` VARCHAR(10) NULL DEFAULT NULL,
  `unique_carrier_name` VARCHAR(100) NULL DEFAULT NULL,
  `unique_carrier_entity` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`airline_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airportdata`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`airport` (
  `airport_ID` INT NOT NULL,
  `airport_seq_ID` INT NULL DEFAULT NULL,
  `city_market_ID` INT NULL DEFAULT NULL,
  `airport_code` VARCHAR(100) NULL DEFAULT NULL,
  `city_name` VARCHAR(100) NULL DEFAULT NULL,
  `state_abr` CHAR(2) NULL DEFAULT NULL,
  `state_fips` INT NULL DEFAULT NULL,
  `state_nm` VARCHAR(100) NULL DEFAULT NULL,
  `wac` INT NULL DEFAULT NULL,
  PRIMARY KEY (`airport_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airportdata`.`airport_project_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`airport_project_data` (
  `PASSENGERS` DOUBLE NULL DEFAULT NULL,
  `FREIGHT` TEXT NULL DEFAULT NULL,
  `MAIL` DOUBLE NULL DEFAULT NULL,
  `DISTANCE` DOUBLE NULL DEFAULT NULL,
  `UNIQUE_CARRIER` TEXT NULL DEFAULT NULL,
  `AIRLINE_ID` INT NULL DEFAULT NULL,
  `UNIQUE_CARRIER_NAME` TEXT NULL DEFAULT NULL,
  `UNIQUE_CARRIER_ENTITY` TEXT NULL DEFAULT NULL,
  `REGION` TEXT NULL DEFAULT NULL,
  `CARRIER` TEXT NULL DEFAULT NULL,
  `CARRIER_NAME` TEXT NULL DEFAULT NULL,
  `CARRIER_GROUP` INT NULL DEFAULT NULL,
  `CARRIER_GROUP_NEW` INT NULL DEFAULT NULL,
  `ORIGIN_AIRPORT_ID` INT NULL DEFAULT NULL,
  `ORIGIN_AIRPORT_SEQ_ID` INT NULL DEFAULT NULL,
  `ORIGIN_CITY_MARKET_ID` INT NULL DEFAULT NULL,
  `ORIGIN` TEXT NULL DEFAULT NULL,
  `ORIGIN_CITY_NAME` TEXT NULL DEFAULT NULL,
  `ORIGIN_STATE_ABR` TEXT NULL DEFAULT NULL,
  `ORIGIN_STATE_FIPS` TEXT NULL DEFAULT NULL,
  `ORIGIN_STATE_NM` TEXT NULL DEFAULT NULL,
  `ORIGIN_WAC` INT NULL DEFAULT NULL,
  `DEST_AIRPORT_ID` INT NULL DEFAULT NULL,
  `DEST_AIRPORT_SEQ_ID` INT NULL DEFAULT NULL,
  `DEST_CITY_MARKET_ID` INT NULL DEFAULT NULL,
  `DEST` TEXT NULL DEFAULT NULL,
  `DEST_CITY_NAME` TEXT NULL DEFAULT NULL,
  `DEST_STATE_ABR` TEXT NULL DEFAULT NULL,
  `DEST_STATE_FIPS` TEXT NULL DEFAULT NULL,
  `DEST_STATE_NM` TEXT NULL DEFAULT NULL,
  `DEST_WAC` INT NULL DEFAULT NULL,
  `YEAR` INT NULL DEFAULT NULL,
  `QUARTER` INT NULL DEFAULT NULL,
  `MONTH` INT NULL DEFAULT NULL,
  `DISTANCE_GROUP` INT NULL DEFAULT NULL,
  `CLASS` TEXT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airportdata`.`all_city_pop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`all_city_pop` (
  `city_name` TEXT NULL DEFAULT NULL,
  `Population` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airportdata`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`city` (
  `CityID` INT NOT NULL DEFAULT '0',
  `City_Name` VARCHAR(100) NULL DEFAULT NULL,
  `State_ABR` CHAR(2) NULL DEFAULT NULL,
  `state_nm` VARCHAR(100) NULL DEFAULT NULL,
  `Population` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airportdata`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`flight` (
  `flight_ID` INT NOT NULL AUTO_INCREMENT,
  `airline_ID` INT NULL DEFAULT NULL,
  `Origin_airport_ID` INT NULL DEFAULT NULL,
  `Dest_airport_ID` INT NULL DEFAULT NULL,
  `distance` FLOAT NULL DEFAULT NULL,
  `distance_group` INT NULL DEFAULT NULL,
  `year` INT NULL DEFAULT NULL,
  `quarter` INT NULL DEFAULT NULL,
  `month` INT NULL DEFAULT NULL,
  `class` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`flight_ID`),
  INDEX `airline_ID` (`airline_ID` ASC) VISIBLE,
  INDEX `Origin_airport_ID` (`Origin_airport_ID` ASC) VISIBLE,
  INDEX `Dest_airport_ID` (`Dest_airport_ID` ASC) VISIBLE,
  CONSTRAINT `flight_ibfk_1`
    FOREIGN KEY (`airline_ID`)
    REFERENCES `airportdata`.`airline` (`airline_ID`),
  CONSTRAINT `flight_ibfk_2`
    FOREIGN KEY (`Origin_airport_ID`)
    REFERENCES `airportdata`.`airport` (`airport_ID`),
  CONSTRAINT `flight_ibfk_3`
    FOREIGN KEY (`Dest_airport_ID`)
    REFERENCES `airportdata`.`airport` (`airport_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 52694
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airportdata`.`flightmatrics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`flightmatrics` (
  `flight_ID` INT NULL DEFAULT NULL,
  `passengers` FLOAT NULL DEFAULT NULL,
  `freight` FLOAT NULL DEFAULT NULL,
  `mail` FLOAT NULL DEFAULT NULL,
  INDEX `flight_ID` (`flight_ID` ASC) VISIBLE,
  CONSTRAINT `flightmatrics_ibfk_1`
    FOREIGN KEY (`flight_ID`)
    REFERENCES `airportdata`.`flight` (`flight_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `airportdata` ;

-- -----------------------------------------------------
-- Placeholder table for view `airportdata`.`passengers_pop_des`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`passengers_pop_des` (`City_Name` INT, `Population` INT, `Total_Passengers` INT, `Total_Flights` INT, `Passengers_Pop_Ration` INT);

-- -----------------------------------------------------
-- Placeholder table for view `airportdata`.`passengers_pop_origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airportdata`.`passengers_pop_origin` (`City_Name` INT, `Population` INT, `Total_Passengers` INT, `Passengers_Pop_Ration` INT);

-- -----------------------------------------------------
-- procedure State_Level_traffic
-- -----------------------------------------------------

DELIMITER $$
USE `airportdata`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `State_Level_traffic`(IN state VARCHAR(30))
BEGIN
    SELECT 
        a.city_name AS origin_city,
        SUM(fm.passengers) AS total_passengers,
        COUNT(f.flight_ID) AS total_flights
    FROM flight f
    JOIN flightMatrics fm ON f.flight_ID = fm.flight_ID
    JOIN airport a ON f.dest_airport_ID = a.airport_ID
    WHERE a.state_nm = state 
    GROUP BY a.city_name
    ORDER BY total_flights DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_top_routes_by_passenger
-- -----------------------------------------------------

DELIMITER $$
USE `airportdata`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_top_routes_by_passenger`(IN threshold INT)
BEGIN
    SELECT 
        a1.city_name AS origin_city,
        a2.city_name AS dest_city,
        SUM(fm.passengers) AS total_passengers
    FROM flight f
    JOIN flightMatrics fm ON f.flight_ID = fm.flight_ID
    JOIN airport a1 ON f.Origin_airport_ID = a1.airport_ID
    JOIN airport a2 ON f.Dest_airport_ID = a2.airport_ID
    GROUP BY a1.city_name, a2.city_name
    HAVING total_passengers > threshold
    ORDER BY total_passengers DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure traffic
-- -----------------------------------------------------

DELIMITER $$
USE `airportdata`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `traffic`()
BEGIN
    SELECT 
        a.city_name AS origin_city,
        SUM(fm.passengers) AS total_passengers,
        COUNT(f.flight_ID) AS total_flights
    FROM flight f
    JOIN flightMatrics fm ON f.flight_ID = fm.flight_ID
    JOIN airport a ON f.dest_airport_ID = a.airport_ID  -- YES this is fine
    GROUP BY a.city_name
    ORDER BY total_flights DESC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `airportdata`.`passengers_pop_des`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airportdata`.`passengers_pop_des`;
USE `airportdata`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `airportdata`.`passengers_pop_des` AS select `c`.`City_Name` AS `City_Name`,`c`.`Population` AS `Population`,sum(`fm`.`passengers`) AS `Total_Passengers`,count(`f`.`flight_ID`) AS `Total_Flights`,round((sum(`fm`.`passengers`) / `c`.`Population`),2) AS `Passengers_Pop_Ration` from (((`airportdata`.`city` `c` join `airportdata`.`airport` `a` on((`a`.`city_name` = `c`.`City_Name`))) join `airportdata`.`flight` `f` on((`f`.`Dest_airport_ID` = `a`.`airport_ID`))) join `airportdata`.`flightmatrics` `fm` on((`f`.`flight_ID` = `fm`.`flight_ID`))) group by `c`.`City_Name`,`c`.`Population` order by `Passengers_Pop_Ration` desc;

-- -----------------------------------------------------
-- View `airportdata`.`passengers_pop_origin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airportdata`.`passengers_pop_origin`;
USE `airportdata`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `airportdata`.`passengers_pop_origin` AS select `c`.`City_Name` AS `City_Name`,`c`.`Population` AS `Population`,sum(`fm`.`passengers`) AS `Total_Passengers`,round((sum(`fm`.`passengers`) / `c`.`Population`),2) AS `Passengers_Pop_Ration` from (((`airportdata`.`city` `c` join `airportdata`.`airport` `a` on((`a`.`city_name` = `c`.`City_Name`))) join `airportdata`.`flight` `f` on((`f`.`Origin_airport_ID` = `a`.`airport_ID`))) join `airportdata`.`flightmatrics` `fm` on((`f`.`flight_ID` = `fm`.`flight_ID`))) group by `c`.`City_Name`,`c`.`Population` order by `Passengers_Pop_Ration` desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
